services:
  postgres:
    image: postgres:15-alpine
  redis:
    image: redis:alpine
  eureka-server:
    build: ./eureka-server
    ports: ["8761:8761"]
  etudiant-service:
    build: ./api-spring-boot
    ports: ["8081:8081"]
    depends_on: [postgres, redis, eureka-server]
  grading-service:
    build: ./grading-service
    ports: ["8082:8082"]
    depends_on: [postgres, eureka-server]
  api-gateway:
    build: ./api-gateway
    ports: ["8080:8080"]
    depends_on: [eureka-server]
  frontend:
    build: ./frontend
    ports: ["3000:3000"]
    depends_on: [api-gateway]
